name: Markdown autodocs
description: 'A github action that automatically format markdown files, sync external docs/src code & make better docs.'

author: Dinesh Sonachalam <dineshsonachalam@gmail.com>

inputs:
  commit_author:
    description: Value used for the commit author. Defaults to the username of whoever triggered this workflow run.
    required: false
    default: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
  commit_user_email:
    description: Email address used for the commit user
    required: false
    default: actions@github.com
  commit_message:
    description: Commit message
    required: false
    default: Apply automatic changes
  branch:
    description: Git branch name, where changes should be pushed too.
    required: false
    default: ${{ github.ref }}

runs:
  using: composite
  steps:
    - run: wget https://raw.githubusercontent.com/dineshsonachalam/markdown-autodocs/master/action.py
      shell: bash
    - run: python3 action.py -repo '${{ github.repository }}' -access_token '${{ github.token }}' -commit_author '${{ inputs.commit_author  }}' -commit_user_email '${{ inputs.commit_user_email  }}' -commit_message '${{ inputs.commit_message  }}' -branch '${{ inputs.branch }}' -output_file_paths '${{ inputs.output_file_paths }}' -categories '${{ inputs.categories }}'
      shell: bash

branding:
  icon: 'book'
  color: blue
