name: markdown-autodocs

on:
  push:
    branches:    
      - '**'  # matches every branch

jobs:        
  autoupdate-readme:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Markdown autodocs
          uses: ./ # Uses an action in the root directory
